### ISSUE TITLE
Question regarding slave implementation

### ISSUE THREAD

**Issue by maid92** [shreaker/OpenXCP#1]
Very nice Thesis and implenentation. Helped me a lot to better understand how the ethernet communication with Aurix works. I am a student and also trying to implement XCP on an Aurix TC277 but I got some questions regarding the slave implementation:

1. In ipStackAurix.c you used header files:
#include "Ifx_Lwip.h"
#include <Tft/conio_tft.h>
#include "HM_Config.h"
But I could not find those files anywhere online. Could you please provide those header files too?

 2. I noticed that the ipStackAurix.h is not used anywhere in the provided files. Does it have to be implemented somewhere? I am just wondering if you used only the files you provided on github or also some additional files.

**Comment by shreaker** [comment]
@maid92 
These files are proprietary and therefore can not be shared on github, sorry.
Files can be obtained from Infineon and lwIP (lightweight IP). 
Please contact me directly via Email or drop a message here for further help regarding this topic.

**Comment by Jelhe32** [comment]
I'm preparing a project for some students and would like to use your code as base to start for them. 

I got lwIP from the example project:
 Ethernet_1 for KIT_AURIX_TC397_TFT Echo application via TCP/IP

In the example gEth is used, which I can't use on TC277. Is there a way, without modifying the example code, to use Eth instead of gEth?
which way did you go?

@maid92 did you found a solution?
